### ISSUE TITLE
Is this project completed or working production?

### ISSUE THREAD

**Issue by mhbu50** [bailabs/erpnext-sync#1]
@ccfiel I need to test this app, I liked it.
Could you help me with the steps to use it?

**Comment by ccfiel** [comment]
@mhbu50 follow the instruction here. https://github.com/bailabs/tailpos

**Comment by mhbu50** [comment]
@ccfiel Thank you for the fast reply, I need to Sync Database Master/Slave.
There is no need to use POS in my scenario.
Do you have instruction for this app?
